### ISSUE TITLE
【请教】富文本编辑器用的什么？

### ISSUE THREAD

**Issue by youngjuning** [Honye/weapp-mark#1]

**Comment by Hongye567** [comment]
抱歉，还没用过

**Comment by youngjuning** [comment]
意思是demo 里边的文章手写的HTML？

**Comment by Hongye567** [comment]
那是后台编辑的，前台（小程序）还没有发布文章的功能，可能以后会添加吧，你可以先进群（[139122611](https://jq.qq.com/?_wv=1027&k=5E8Kajz)）问问是否已经有人使用了

**Comment by youngjuning** [comment]
其实我问的就是后台

**Comment by Hongye567** [comment]
后台网上就狠多了，[百度 UEditor](http://ueditor.baidu.com/website/)
