### ISSUE TITLE
云数据库都有哪些表

### ISSUE THREAD

**Issue by ahaochina** [Honye/weapp-mark#12]
云数据库都有哪些表，表都有哪些项？

**Comment by Johnnyhj** [comment]
跑不起来额。大家能跑起来嘛？


app.js错误:
 Error: module "store/mobx-miniprogram" is not defined
    at require (VM803 WAService.js:2)
    at VM803 WAService.js:2
    at index.js? [sm]:4

**Comment by Honye** [comment]
> 云数据库都有哪些表，表都有哪些项？

已解决，无需初始化云表也能正常使用了
