### ISSUE TITLE
请教：如何打开预览项目？

### ISSUE THREAD

**Issue by hanyucd** [Honye/weapp-mark#4]
![image](https://user-images.githubusercontent.com/13725830/81999181-edf10080-9686-11ea-9c24-1553254259a5.png)

**Comment by Honye** [comment]
项目中使用到了云函数，需要初始化几张表：

| 集合名           | 等等         |
| :--------------- | :----------- |
| articleRelations | 文章关联集合 |
| articles         | 文章集合     |
| banners          | banne 集合   |
| cardRelations    | 卡片关联集合 |
| cards            | 卡片集合     |
| categories       | 类别集合     |
| userRelations    | 用户关联集合 |

**Comment by hanyucd** [comment]
@Honye 那是不是得在我自己的云开发环境下，上传云函数 、初始化数据集合 并且修改 app.js 下的初始化云环境
![image](https://user-images.githubusercontent.com/13725830/82403177-ccca4e80-9a90-11ea-95e5-66a5e072372b.png)
