### ISSUE TITLE
萌新求助

### ISSUE THREAD

**Issue by toff1027** [Honye/weapp-mark#41]
![屏幕截图 2022-09-26 140146](https://user-images.githubusercontent.com/80618776/192206986-6b9a04f7-7ff2-44e8-9f83-2849cb4aa315.png)

**Comment by Honye** [comment]
@toff1027 你未同步云函数至云。开通云开发后，同步 `/cloudfundtions` 至云

**Comment by toff1027** [comment]
> /cloudfundtions

![image](https://user-images.githubusercontent.com/80618776/192227534-b523d188-9da7-4d9d-983d-2d9cb34d1a4f.png)
点那个云同步吗，云同步之后还是报错啊

**Comment by Honye** [comment]
@toff1027 贴报错信息

**Comment by toff1027** [comment]
> 同步 `/cloudfundtions` 至云

![image](https://user-images.githubusercontent.com/80618776/192245033-710c4759-ade7-435e-ab7c-834ba7b78cb6.png)
hais还是之前那个报错，之前也是同步了的

**Comment by Honye** [comment]
@Honye 看错误信息是未找到该云函数，你检查下云开发控制台，看看是否存在该云函数
