### ISSUE TITLE
【求助咨询🙏】项目启动后变成壁纸项目

### ISSUE THREAD

**Issue by CVnot** [Honye/weapp-mark#60]
首先非常感谢将这么优秀的代码开源，所以想把他run起来
![image](https://github.com/user-attachments/assets/6bcfc4b4-8ca8-4b1a-bc2b-49338e287f2e)
按照gitee上的步骤启动后，项目就变成这样了🥹，看代码像是从360里面拿壁纸，但不知道为啥后面的页面渲染逻辑都不走了

**Comment by CVnot** [comment]
首屏加载的那张炫酷的登陆图片倒是可以渲染出来。

**Comment by Honye** [comment]
降低 `miniprogram/store/app.js` 中的版本号

**Comment by CVnot** [comment]
感谢答复，修改version到0就可以了。
