### ISSUE TITLE
潜在兼容性bug

### ISSUE THREAD

**Issue by 598807302** [Honye/weapp-mark#7]
在项目中，发现没有使用wx.getSystemInfo这个API去获取使用机型的系统信息。
然后通过windowWidth，windowHeight和safeArea来调整小程序的布局设置。

没有通过wx.getSystemInfo的适配，在部分机型上可能会出现一些样式问题。

您好，方便确认一下该问题吗。

**Comment by Honye** [comment]
什么机型存在问题呢？
iPhone 的下巴项目中是有适配的。参考 `style/common.wxss`

https://github.com/Honye/weapp-mark/blob/ea344aefe6f13b2d8cb26b0d2cb07d527533f943/miniprogram/style/common.wxss#L134-L148

在需要适配 iPhone 下巴的地方放一个占位元素就好，如：

```xml
<view class="container">
  <view class="fixed-bottom">
    <view>固定在底部的内容</view>
    <view class="iphonex-bottom-holder"><!-- iPhone 下巴占位 --></view>
  </view>
</view>
```

**Comment by 598807302** [comment]
您好我是直接从代码中去看的没有注意样式代码，不好意思。
之前看到的问题的确在IPhoneX系统较多，还有部分刘海屏手机的头部导航栏也可能有一些显示问题。
