### ISSUE TITLE
导入到微信开发者工具后提示这个错误

### ISSUE THREAD

**Issue by heyzayz** [Honye/weapp-mark#8]
导入到微信开发者工具后提示这个错误
![image](https://user-images.githubusercontent.com/11624033/114349982-281a9900-9b9b-11eb-9f61-36e0147ffeb2.png)

**Comment by Honye** [comment]
项目中有使用到 npm 包，参考微信官文 [npm 支持](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html)

**Comment by heyzayz** [comment]
那个可以了，这个是因为什么，需要部署哪些云函数

![image](https://user-images.githubusercontent.com/11624033/114378481-5491dd80-9bba-11eb-8b33-0e92a8b4cd00.png)

**Comment by Honye** [comment]
@heyzayz 需要开通云开发环境并同步 `/cloufunctions/` 至云，说明文档已更新
